# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Ramesh!"

In [ ]:
print(s.split())

['Hi', 'there', 'Ramesh!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of {} is {} kilometer.".format(planet,diameter))

The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hi"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hi']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hi


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 5 Zero's? 
## 4.2 Create an array of 20 Two's?

In [ ]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
print(np.ones(20)*2)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


## 5. Create an array of all the even integers from 10 to 25

In [ ]:
print(np.arange(10,25,5))

[10 15 20]


## 6. Create a 4x4 matrix with values ranging from 0 to 15

In [ ]:
print(np.arange(0,16).reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 1 column

In [26]:
import pandas as pd


In [ ]:
data = [10,20,30]
df=pd.DataFrame(data, columns=['numbers'])
print(df)

   numbers
0       10
1       20
2       30


## 9. Generate the series of dates from 1st Jan, 2023 to 1st Feb, 2023

In [30]:
import datetime
test_date= datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
K = 32
date_gen=pd.date_range(test_date,periods=K)
print(date_gen.strftime("%d-%m-%Y"))
  

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'xxx', 11],
         [2, 'yyy', 22],
         [3, 'zzz', 33]]

In [ ]:
lists = [[1, 'xxx', 11], [2, 'yyy', 22], [3, 'zzz', 33]]

In [ ]:
df = pd.DataFrame(lists, columns =['sno','name', 'value'])
print(df )

   sno name  value
0    1  xxx     11
1    2  yyy     22
2    3  zzz     33
